[workspace]
resolver = "3"
members = [
  "packages/core",
  "packages/ctap",
  "packages/host-browser",
  "packages/host-client",
  "packages/host-desktop",
  "packages/kdbx",
  "packages/kdbx-debug",
  "packages/lesswire",
  "packages/native-ui",
  "packages/schema",
  "packages/secure-types",
  "packages/sync"
]
