[workspace]
resolver = "3"
members = [
  "packages/core",
  "packages/desktop/crates/keeless_daemon",
  "packages/desktop/crates/keeless_desktop_ipc",
  "packages/desktop/src-tauri",
  "packages/host-browser",
  "packages/kdbx",
  "packages/kdbx-debug",
  "packages/schema",
  "packages/secure-types",
  "packages/sync"
]
