// Generated by `pnpm generate`. Do not edit.

export type StorageDescriptor = { provider: string; path: string };

/**
 * Plaintext metadata used to present a recently opened database before unlock.
 */
export type RecentDatabase = {
  id: string;
  name: string;
  storageType: string;
  lastOpenedAtMs: number;
};

export type DatabaseStatus = 'not_exist' | 'locked' | 'unlocked';

export type SyncStatus = 'idle' | 'syncing' | 'error';

export type KeyScope = 'core_untrusted' | 'core' | 'app' | 'passkey' | 'native_ui';

export type KeelessConfig = { autoLockTimeoutMs: number | null; paranoiaMode: boolean };

export type KeelessConfigPatch = { autoLockTimeoutMs?: number | null; paranoiaMode?: boolean };

export type DatabaseNodeId = string | number;

export type IconReference = { standardId: number; customUuid: string | null };

export type EntrySummary = {
  id: DatabaseNodeId;
  name: string | null;
  nameIsProtected: boolean;
  username: string | null;
  usernameIsProtected: boolean;
  url: string | null;
  urlIsProtected: boolean;
  icon: IconReference;
  tags: string[];
};

export type CustomIcon = {
  uuid: string;
  dataBase64: string;
  name: string;
  lastModificationTimeMs: number;
};

export type GroupHierarchyItem = {
  id: DatabaseNodeId;
  name: string;
  icon: IconReference;
  childGroupIds: DatabaseNodeId[];
};

export type TagStyle = { icon: IconReference; color: string };

export type TagSummary = {
  name: string;
  entryCount: number;
  style: TagStyle | null;
  canDelete: boolean;
};

export type EntryFieldKind = 'title' | 'userName' | 'password' | 'url' | 'notes' | 'custom';

export type EntryFieldInformation =
  | {
      type: 'field';
      order: number;
      fieldId: string | null;
      kind: EntryFieldKind;
      name: string;
      label: string;
      value: string | null;
      isProtected: boolean;
      isInternal: boolean;
      control: FieldControl | null;
    }
  | { type: 'timeOtp'; order: number; label: string }
  | {
      type: 'passwordConfirmation';
      order: number;
      label: string;
      passwordFieldId: string;
      control: FieldControl;
    }
  | { type: 'overrideUrl'; order: number; label: string; control: FieldControl }
  | { type: 'expiry'; order: number; label: string; control: FieldControl }
  | { type: 'tags'; order: number; label: string; control: FieldControl }
  | { type: 'divider'; order: number; label: string };

export type EntryAttachmentInformation = {
  index: number;
  name: string;
  size: number;
  isProtected: boolean;
};

export type FieldControl =
  | { type: 'text'; protected: boolean; lines: number }
  | { type: 'url' }
  | { type: 'popout'; protected: boolean }
  | { type: 'richText'; lines: number }
  | { type: 'date' }
  | { type: 'time' }
  | { type: 'dateTime' }
  | { type: 'checkbox' }
  | { type: 'select'; options: string[] }
  | { type: 'divider' };

export type OpenArgs = { storage: StorageDescriptor } | { databaseId: string };

export type GetRecentDatabasesArgs = Record<string, never>;

export type DeleteRecentDatabaseArgs = { id: string };

export type CreateArgs = { password?: string | null };

export type UnlockArgs = { password?: string | null };

export type LockArgs = { password?: string | null };

export type GetDatabaseStatusArgs = Record<string, never>;

export type GetCoreStatusArgs = Record<string, never>;

export type UpgradeArgs = Record<string, never>;

export type GetStorageProviderArgs = Record<string, never>;

export type GetConfigArgs = Record<string, never>;

export type SetConfigArgs = { config: KeelessConfigPatch };

export type GetEntriesArgs = { excludeTrash?: boolean };

export type SearchEntriesArgs = { query: string };

export type SearchFuzzyArgs = { query: string };

export type GetGroupHierarchyArgs = Record<string, never>;

export type GetGroupEntriesArgs = { groupId: DatabaseNodeId };

export type GetTagEntriesArgs = { tag: string };

export type GetTrashEntriesArgs = Record<string, never>;

export type GetTagsArgs = Record<string, never>;

export type GetEntryDetailArgs = { entryId: DatabaseNodeId };

export type EntryFieldUpdate = {
  fieldId: string | null;
  name: string;
  value: string | null;
  isProtected: boolean;
};

export type EntryPropertiesUpdate = {
  overrideUrl: string;
  tags: string[];
  expires: boolean;
  expiryTimeMs: number | null;
  icon?: IconReference | null;
};

export type EntryAttachmentUpdate = { transferId: string; name: string };

export type UpdateEntryArgs = {
  entryId: DatabaseNodeId;
  fields: EntryFieldUpdate[];
  properties?: EntryPropertiesUpdate | null;
  attachments?: EntryAttachmentUpdate[] | null;
  removedAttachmentIndices?: number[] | null;
  password?: string | null;
};

export type PrepareEntryAttachmentDownloadArgs = {
  entryId: DatabaseNodeId;
  attachmentIndex: number;
  name: string;
};

export type DeleteEntryArgs = { entryId: DatabaseNodeId; permanent: boolean };

export type EmptyRecycleBinArgs = Record<string, never>;

export type SaveDatabaseArgs = { password?: string | null };

export type PrepareDatabaseExportArgs = { password?: string | null };

export type MergeTransferredDatabaseArgs = {
  transferId: string;
  sourcePassword: string;
  password?: string | null;
};

export type GetCustomIconsArgs = Record<string, never>;

export type GetEntryTemplatesArgs = Record<string, never>;

export type MoveGroupArgs = {
  groupId: DatabaseNodeId;
  parentGroupId: DatabaseNodeId;
  destinationIndex: number;
};

export type MoveEntryArgs = { entryId: DatabaseNodeId; parentGroupId: DatabaseNodeId };

export type AddEntryArgs = { parentGroupId: DatabaseNodeId };

export type AddEntryFromTemplateArgs = {
  parentGroupId: DatabaseNodeId;
  templateEntryId: DatabaseNodeId;
};

export type AddGroupArgs = { parentGroupId: DatabaseNodeId };

export type DeleteGroupArgs = { groupId: DatabaseNodeId };

export type RenameGroupArgs = { groupId: DatabaseNodeId; name: string };

export type UpdateGroupArgs = { groupId: DatabaseNodeId; name: string; icon: IconReference };

export type UpdateTagStyleArgs = { name: string; style: TagStyle };

export type DeleteTagArgs = { name: string };

export type RevealEntryFieldsArgs = {
  entryId: DatabaseNodeId;
  fieldIds: string[];
  password?: string | null;
};

export type GetEntryTotpArgs = {
  entryId: DatabaseNodeId;
  fieldId?: string | null;
  password?: string | null;
};

export type GetPasskeysArgs = { rpId?: string | null; allowCredentialIds?: string[] };

export type RegisterPasskeyArgs = {
  rpId: string;
  rpName?: string | null;
  userName: string;
  userHandle: string;
  clientDataHash: string;
  algorithms: number[];
  excludeCredentialIds: string[];
};

export type AssertPasskeyArgs = {
  rpId: string;
  clientDataHash: string;
  allowCredentialIds?: string[];
  userPresent: boolean;
};

export type Operation =
  | { op: 'open'; args: OpenArgs }
  | { op: 'getRecentDatabases'; args: GetRecentDatabasesArgs }
  | { op: 'deleteRecentDatabase'; args: DeleteRecentDatabaseArgs }
  | { op: 'create'; args: CreateArgs }
  | { op: 'unlock'; args: UnlockArgs }
  | { op: 'lock'; args: LockArgs }
  | { op: 'getCoreStatus'; args: GetCoreStatusArgs }
  | { op: 'upgrade'; args: UpgradeArgs }
  | { op: 'getDatabaseStatus'; args: GetDatabaseStatusArgs }
  | { op: 'getStorageProvider'; args: GetStorageProviderArgs }
  | { op: 'getConfig'; args: GetConfigArgs }
  | { op: 'setConfig'; args: SetConfigArgs }
  | { op: 'getEntries'; args: GetEntriesArgs }
  | { op: 'searchEntries'; args: SearchEntriesArgs }
  | { op: 'searchFuzzy'; args: SearchFuzzyArgs }
  | { op: 'getGroupHierarchy'; args: GetGroupHierarchyArgs }
  | { op: 'getGroupEntries'; args: GetGroupEntriesArgs }
  | { op: 'getTagEntries'; args: GetTagEntriesArgs }
  | { op: 'getTrashEntries'; args: GetTrashEntriesArgs }
  | { op: 'getTags'; args: GetTagsArgs }
  | { op: 'getEntryDetail'; args: GetEntryDetailArgs }
  | { op: 'updateEntry'; args: UpdateEntryArgs }
  | { op: 'prepareEntryAttachmentDownload'; args: PrepareEntryAttachmentDownloadArgs }
  | { op: 'deleteEntry'; args: DeleteEntryArgs }
  | { op: 'emptyRecycleBin'; args: EmptyRecycleBinArgs }
  | { op: 'saveDatabase'; args: SaveDatabaseArgs }
  | { op: 'prepareDatabaseExport'; args: PrepareDatabaseExportArgs }
  | { op: 'mergeTransferredDatabase'; args: MergeTransferredDatabaseArgs }
  | { op: 'getCustomIcons'; args: GetCustomIconsArgs }
  | { op: 'getEntryTemplates'; args: GetEntryTemplatesArgs }
  | { op: 'moveGroup'; args: MoveGroupArgs }
  | { op: 'moveEntry'; args: MoveEntryArgs }
  | { op: 'addEntry'; args: AddEntryArgs }
  | { op: 'addEntryFromTemplate'; args: AddEntryFromTemplateArgs }
  | { op: 'addGroup'; args: AddGroupArgs }
  | { op: 'deleteGroup'; args: DeleteGroupArgs }
  | { op: 'renameGroup'; args: RenameGroupArgs }
  | { op: 'updateGroup'; args: UpdateGroupArgs }
  | { op: 'updateTagStyle'; args: UpdateTagStyleArgs }
  | { op: 'deleteTag'; args: DeleteTagArgs }
  | { op: 'revealEntryFields'; args: RevealEntryFieldsArgs }
  | { op: 'getEntryTotp'; args: GetEntryTotpArgs }
  | { op: 'getPasskeys'; args: GetPasskeysArgs }
  | { op: 'registerPasskey'; args: RegisterPasskeyArgs }
  | { op: 'assertPasskey'; args: AssertPasskeyArgs };

export type OperationRequest = (
  | { op: 'open'; args: OpenArgs }
  | { op: 'getRecentDatabases'; args: GetRecentDatabasesArgs }
  | { op: 'deleteRecentDatabase'; args: DeleteRecentDatabaseArgs }
  | { op: 'create'; args: CreateArgs }
  | { op: 'unlock'; args: UnlockArgs }
  | { op: 'lock'; args: LockArgs }
  | { op: 'getCoreStatus'; args: GetCoreStatusArgs }
  | { op: 'upgrade'; args: UpgradeArgs }
  | { op: 'getDatabaseStatus'; args: GetDatabaseStatusArgs }
  | { op: 'getStorageProvider'; args: GetStorageProviderArgs }
  | { op: 'getConfig'; args: GetConfigArgs }
  | { op: 'setConfig'; args: SetConfigArgs }
  | { op: 'getEntries'; args: GetEntriesArgs }
  | { op: 'searchEntries'; args: SearchEntriesArgs }
  | { op: 'searchFuzzy'; args: SearchFuzzyArgs }
  | { op: 'getGroupHierarchy'; args: GetGroupHierarchyArgs }
  | { op: 'getGroupEntries'; args: GetGroupEntriesArgs }
  | { op: 'getTagEntries'; args: GetTagEntriesArgs }
  | { op: 'getTrashEntries'; args: GetTrashEntriesArgs }
  | { op: 'getTags'; args: GetTagsArgs }
  | { op: 'getEntryDetail'; args: GetEntryDetailArgs }
  | { op: 'updateEntry'; args: UpdateEntryArgs }
  | { op: 'prepareEntryAttachmentDownload'; args: PrepareEntryAttachmentDownloadArgs }
  | { op: 'deleteEntry'; args: DeleteEntryArgs }
  | { op: 'emptyRecycleBin'; args: EmptyRecycleBinArgs }
  | { op: 'saveDatabase'; args: SaveDatabaseArgs }
  | { op: 'prepareDatabaseExport'; args: PrepareDatabaseExportArgs }
  | { op: 'mergeTransferredDatabase'; args: MergeTransferredDatabaseArgs }
  | { op: 'getCustomIcons'; args: GetCustomIconsArgs }
  | { op: 'getEntryTemplates'; args: GetEntryTemplatesArgs }
  | { op: 'moveGroup'; args: MoveGroupArgs }
  | { op: 'moveEntry'; args: MoveEntryArgs }
  | { op: 'addEntry'; args: AddEntryArgs }
  | { op: 'addEntryFromTemplate'; args: AddEntryFromTemplateArgs }
  | { op: 'addGroup'; args: AddGroupArgs }
  | { op: 'deleteGroup'; args: DeleteGroupArgs }
  | { op: 'renameGroup'; args: RenameGroupArgs }
  | { op: 'updateGroup'; args: UpdateGroupArgs }
  | { op: 'updateTagStyle'; args: UpdateTagStyleArgs }
  | { op: 'deleteTag'; args: DeleteTagArgs }
  | { op: 'revealEntryFields'; args: RevealEntryFieldsArgs }
  | { op: 'getEntryTotp'; args: GetEntryTotpArgs }
  | { op: 'getPasskeys'; args: GetPasskeysArgs }
  | { op: 'registerPasskey'; args: RegisterPasskeyArgs }
  | { op: 'assertPasskey'; args: AssertPasskeyArgs }
) & { requestId: string };

export type EmptyResult = Record<string, never>;

export type RecentDatabasesResult = { databases: RecentDatabase[] };

export type DatabaseStatusResult = {
  status: DatabaseStatus;
  syncStatus: SyncStatus;
  dirty: boolean;
  syncError: OperationError | null;
};

export type CoreStatusResult = { database: DatabaseStatus };

export type UpgradeResult = { publicKey: string };

export type StorageProviderResult = { provider: string | null };

export type ConfigResult = { config: KeelessConfig };

export type EntriesResult = { entries: EntrySummary[] };

export type SearchFuzzyResult = {
  entries: EntrySummary[];
  groups: GroupHierarchyItem[];
  tags: TagSummary[];
  trashMatches: boolean;
  filterTokens: string[];
};

export type GroupHierarchyResult = {
  databaseName: string;
  rootGroupId: DatabaseNodeId;
  recycleBinId: DatabaseNodeId | null;
  groups: GroupHierarchyItem[];
};

export type TagsResult = { tags: TagSummary[] };

export type EntryDetailResult = {
  id: DatabaseNodeId;
  isTemplate: boolean;
  icon: IconReference;
  tags: string[];
  fields: EntryFieldInformation[];
  backgroundColor: string;
  foregroundColor: string;
  overrideUrl: string;
  creationTimeMs: number | null;
  lastModificationTimeMs: number | null;
  lastAccessTimeMs: number | null;
  locationChangedMs: number | null;
  expires: boolean;
  expiryTimeMs: number | null;
  usageCount: number;
  attachments: EntryAttachmentInformation[];
};

export type CustomIconsResult = { icons: CustomIcon[] };

export type AddEntryResult = { id: DatabaseNodeId };

export type AddGroupResult = { id: DatabaseNodeId };

export type PrepareDatabaseExportResult = { transferId: string };

export type PrepareEntryAttachmentDownloadResult = { transferId: string };

export type MergeTransferredDatabaseResult = {
  entriesAdded: number;
  entriesModified: number;
  entriesDeleted: number;
  groupsAdded: number;
  groupsModified: number;
  groupsDeleted: number;
  conflictCount: number;
  syncError: OperationError | null;
};

export type RevealEntryFieldsResult = { values: string[] };

export type GetEntryTotpResult = {
  code: string;
  digits: number;
  period: number;
  expiresAtMs: number;
};

/**
 * One stored passkey, as much as can be shown without signing anything.
 */
export type PasskeySummary = { entryId: DatabaseNodeId; rpId: string; username: string };

export type PasskeysResult = { credentials: PasskeySummary[] };

export type RegisterPasskeyResult = {
  entryId: DatabaseNodeId;
  credentialId: string;
  authenticatorData: string;
};

export type AssertPasskeyResult = {
  credentialId: string;
  authenticatorData: string;
  signature: string;
  userHandle: string;
  userName?: string | null;
  userSelected: boolean;
};

export type OperationSuccess =
  | { op: 'open'; result: EmptyResult }
  | { op: 'getRecentDatabases'; result: RecentDatabasesResult }
  | { op: 'deleteRecentDatabase'; result: EmptyResult }
  | { op: 'create'; result: EmptyResult }
  | { op: 'unlock'; result: EmptyResult }
  | { op: 'lock'; result: EmptyResult }
  | { op: 'getCoreStatus'; result: CoreStatusResult }
  | { op: 'upgrade'; result: UpgradeResult }
  | { op: 'getDatabaseStatus'; result: DatabaseStatusResult }
  | { op: 'getStorageProvider'; result: StorageProviderResult }
  | { op: 'getConfig'; result: ConfigResult }
  | { op: 'setConfig'; result: EmptyResult }
  | { op: 'getEntries'; result: EntriesResult }
  | { op: 'searchEntries'; result: EntriesResult }
  | { op: 'searchFuzzy'; result: SearchFuzzyResult }
  | { op: 'getGroupHierarchy'; result: GroupHierarchyResult }
  | { op: 'getGroupEntries'; result: EntriesResult }
  | { op: 'getTagEntries'; result: EntriesResult }
  | { op: 'getTrashEntries'; result: EntriesResult }
  | { op: 'getTags'; result: TagsResult }
  | { op: 'getEntryDetail'; result: EntryDetailResult }
  | { op: 'updateEntry'; result: EmptyResult }
  | { op: 'prepareEntryAttachmentDownload'; result: PrepareEntryAttachmentDownloadResult }
  | { op: 'deleteEntry'; result: EmptyResult }
  | { op: 'emptyRecycleBin'; result: EmptyResult }
  | { op: 'saveDatabase'; result: EmptyResult }
  | { op: 'prepareDatabaseExport'; result: PrepareDatabaseExportResult }
  | { op: 'mergeTransferredDatabase'; result: MergeTransferredDatabaseResult }
  | { op: 'getCustomIcons'; result: CustomIconsResult }
  | { op: 'getEntryTemplates'; result: EntriesResult }
  | { op: 'moveGroup'; result: EmptyResult }
  | { op: 'moveEntry'; result: EmptyResult }
  | { op: 'addEntry'; result: AddEntryResult }
  | { op: 'addEntryFromTemplate'; result: AddEntryResult }
  | { op: 'addGroup'; result: AddGroupResult }
  | { op: 'deleteGroup'; result: EmptyResult }
  | { op: 'renameGroup'; result: EmptyResult }
  | { op: 'updateGroup'; result: EmptyResult }
  | { op: 'updateTagStyle'; result: EmptyResult }
  | { op: 'deleteTag'; result: EmptyResult }
  | { op: 'revealEntryFields'; result: RevealEntryFieldsResult }
  | { op: 'getEntryTotp'; result: GetEntryTotpResult }
  | { op: 'getPasskeys'; result: PasskeysResult }
  | { op: 'registerPasskey'; result: RegisterPasskeyResult }
  | { op: 'assertPasskey'; result: AssertPasskeyResult };

export type OperationError = { code: string; message: string };

export type OperationOutcome =
  | ({ status: 'success' } & OperationSuccess)
  | { status: 'error'; error: OperationError };

export type OperationResponse = OperationOutcome & { requestId: string };

export type OperationResource =
  | 'databaseStatus'
  | 'recentDatabase'
  | 'storageProvider'
  | 'config'
  | 'entry'
  | 'group'
  | 'tag'
  | 'customIcon';

export type OperationMetadata = {
  queries?: readonly OperationResource[];
  fetches?: readonly OperationResource[];
  mutates?: readonly OperationResource[];
  senders: readonly KeyScope[];
  recipients: readonly KeyScope[];
};

export const operationMetadata = {
  open: {
    mutates: ['databaseStatus'],
    senders: ['app', 'passkey'],
    recipients: ['core_untrusted'],
  },
  getRecentDatabases: {
    queries: ['recentDatabase'],
    senders: ['app'],
    recipients: ['core_untrusted'],
  },
  deleteRecentDatabase: {
    mutates: ['recentDatabase'],
    senders: ['app'],
    recipients: ['core_untrusted'],
  },
  create: {
    mutates: ['databaseStatus'],
    senders: ['core_untrusted', 'core', 'app', 'passkey'],
    recipients: ['core_untrusted'],
  },
  unlock: {
    mutates: ['databaseStatus'],
    senders: ['app', 'passkey'],
    recipients: ['core_untrusted'],
  },
  lock: { mutates: ['databaseStatus'], senders: ['app'], recipients: ['core'] },
  getCoreStatus: {
    queries: ['databaseStatus'],
    senders: ['app', 'passkey'],
    recipients: ['core_untrusted'],
  },
  upgrade: { senders: ['app', 'passkey'], recipients: ['core_untrusted'] },
  getDatabaseStatus: { queries: ['databaseStatus'], senders: ['app'], recipients: ['core'] },
  getStorageProvider: { queries: ['storageProvider'], senders: ['app'], recipients: ['core'] },
  getConfig: { queries: ['config'], senders: ['app'], recipients: ['core'] },
  setConfig: { mutates: ['config', 'databaseStatus'], senders: ['app'], recipients: ['core'] },
  getEntries: { queries: ['entry'], senders: ['app'], recipients: ['core'] },
  searchEntries: { queries: ['entry'], senders: ['app'], recipients: ['core'] },
  searchFuzzy: { queries: ['entry', 'group', 'tag'], senders: ['app'], recipients: ['core'] },
  getGroupHierarchy: { queries: ['group'], senders: ['app'], recipients: ['core'] },
  getGroupEntries: { queries: ['entry'], senders: ['app'], recipients: ['core'] },
  getTagEntries: { queries: ['entry', 'tag'], senders: ['app'], recipients: ['core'] },
  getTrashEntries: { queries: ['entry'], senders: ['app'], recipients: ['core'] },
  getTags: { queries: ['tag'], senders: ['app'], recipients: ['core'] },
  getEntryDetail: { queries: ['entry'], senders: ['app'], recipients: ['core'] },
  updateEntry: {
    mutates: ['databaseStatus', 'entry', 'tag'],
    senders: ['app'],
    recipients: ['core'],
  },
  prepareEntryAttachmentDownload: { fetches: ['entry'], senders: ['app'], recipients: ['core'] },
  deleteEntry: {
    mutates: ['databaseStatus', 'entry', 'tag'],
    senders: ['app'],
    recipients: ['core'],
  },
  emptyRecycleBin: {
    mutates: ['databaseStatus', 'entry', 'group', 'tag'],
    senders: ['app'],
    recipients: ['core'],
  },
  saveDatabase: {
    mutates: ['databaseStatus', 'entry', 'group', 'tag', 'customIcon'],
    senders: ['app'],
    recipients: ['core'],
  },
  prepareDatabaseExport: {
    fetches: ['entry', 'group', 'tag', 'customIcon'],
    senders: ['app'],
    recipients: ['core'],
  },
  mergeTransferredDatabase: {
    mutates: ['databaseStatus', 'entry', 'group', 'tag', 'customIcon'],
    senders: ['app'],
    recipients: ['core'],
  },
  getCustomIcons: { queries: ['customIcon'], senders: ['app'], recipients: ['core'] },
  getEntryTemplates: { queries: ['entry'], senders: ['app'], recipients: ['core'] },
  moveGroup: { mutates: ['databaseStatus', 'group'], senders: ['app'], recipients: ['core'] },
  moveEntry: {
    mutates: ['databaseStatus', 'entry', 'tag'],
    senders: ['app'],
    recipients: ['core'],
  },
  addEntry: { mutates: ['databaseStatus', 'entry', 'tag'], senders: ['app'], recipients: ['core'] },
  addEntryFromTemplate: {
    mutates: ['databaseStatus', 'entry', 'tag'],
    senders: ['app'],
    recipients: ['core'],
  },
  addGroup: { mutates: ['databaseStatus', 'group'], senders: ['app'], recipients: ['core'] },
  deleteGroup: {
    mutates: ['databaseStatus', 'entry', 'group', 'tag'],
    senders: ['app'],
    recipients: ['core'],
  },
  renameGroup: { mutates: ['databaseStatus', 'group'], senders: ['app'], recipients: ['core'] },
  updateGroup: { mutates: ['databaseStatus', 'group'], senders: ['app'], recipients: ['core'] },
  updateTagStyle: { mutates: ['databaseStatus', 'tag'], senders: ['app'], recipients: ['core'] },
  deleteTag: { mutates: ['databaseStatus', 'tag'], senders: ['app'], recipients: ['core'] },
  revealEntryFields: { fetches: ['entry'], senders: ['app'], recipients: ['core'] },
  getEntryTotp: { fetches: ['entry'], senders: ['app'], recipients: ['core'] },
  getPasskeys: { queries: ['entry'], senders: ['app', 'passkey'], recipients: ['core'] },
  registerPasskey: {
    mutates: ['databaseStatus', 'entry'],
    senders: ['app', 'passkey'],
    recipients: ['core'],
  },
  assertPasskey: { fetches: ['entry'], senders: ['app', 'passkey'], recipients: ['core'] },
} as const satisfies Record<Operation['op'], OperationMetadata>;
