// Generated by `cargo run --bin export-types`. Do not edit.

export type StorageDescriptor = { provider: string; path: string };

export type DatabaseStatus = 'not_exist' | 'locked' | 'unlocked';

export type SyncStatus = 'idle' | 'syncing' | 'error';

export type KeelessConfig = { autoLockTimeoutMs: number | null; paranoiaMode: boolean };

export type KeelessConfigPatch = { autoLockTimeoutMs?: number | null; paranoiaMode?: boolean };

export type DatabaseNodeId = string | number;

export type IconReference = { standardId: number; customUuid: string | null };

export type EntrySummary = {
  id: DatabaseNodeId;
  name: string | null;
  nameIsProtected: boolean;
  username: string | null;
  usernameIsProtected: boolean;
  url: string | null;
  urlIsProtected: boolean;
  icon: IconReference;
  tags: string[];
};

export type CustomIcon = {
  uuid: string;
  dataBase64: string;
  name: string;
  lastModificationTimeMs: number;
};

export type GroupHierarchyItem = {
  id: DatabaseNodeId;
  name: string;
  icon: IconReference;
  childGroupIds: DatabaseNodeId[];
};

export type TagStyle = { icon: IconReference; color: string };

export type TagSummary = {
  name: string;
  entryCount: number;
  style: TagStyle | null;
  canDelete: boolean;
};

export type EntryFieldKind = 'title' | 'userName' | 'password' | 'url' | 'notes' | 'custom';

export type EntryFieldInformation =
  | {
      type: 'field';
      order: number;
      fieldId: string | null;
      kind: EntryFieldKind;
      name: string;
      label: string;
      value: string | null;
      isProtected: boolean;
      isInternal: boolean;
      control: FieldControl | null;
    }
  | {
      type: 'passwordConfirmation';
      order: number;
      label: string;
      passwordFieldId: string;
      control: FieldControl;
    }
  | { type: 'overrideUrl'; order: number; label: string; control: FieldControl }
  | { type: 'expiry'; order: number; label: string; control: FieldControl }
  | { type: 'tags'; order: number; label: string; control: FieldControl }
  | { type: 'divider'; order: number; label: string };

export type EntryAttachmentInformation = { name: string; size: number; isProtected: boolean };

export type FieldControl =
  | { type: 'text'; protected: boolean; lines: number }
  | { type: 'url' }
  | { type: 'popout'; protected: boolean }
  | { type: 'richText'; lines: number }
  | { type: 'date' }
  | { type: 'time' }
  | { type: 'dateTime' }
  | { type: 'checkbox' }
  | { type: 'select'; options: string[] }
  | { type: 'divider' };

export type OpenArgs = { storage: StorageDescriptor };

export type CreateArgs = { password?: string | null };

export type UnlockArgs = { password?: string | null };

export type LockArgs = Record<string, never>;

export type GetDatabaseStatusArgs = Record<string, never>;

export type GetStorageDescriptorArgs = Record<string, never>;

export type GetConfigArgs = Record<string, never>;

export type SetConfigArgs = { config: KeelessConfigPatch };

export type GetEntriesArgs = { excludeTrash?: boolean };

export type SearchEntriesArgs = { query: string };

export type GetGroupHierarchyArgs = Record<string, never>;

export type GetGroupEntriesArgs = { groupId: DatabaseNodeId };

export type GetTagEntriesArgs = { tag: string };

export type GetTrashEntriesArgs = Record<string, never>;

export type GetTagsArgs = Record<string, never>;

export type GetEntryDetailArgs = { entryId: DatabaseNodeId };

export type EntryFieldUpdate = {
  fieldId: string | null;
  name: string;
  value: string | null;
  isProtected: boolean;
};

export type EntryPropertiesUpdate = {
  overrideUrl: string;
  tags: string[];
  expires: boolean;
  expiryTimeMs: number | null;
  icon?: IconReference | null;
};

export type UpdateEntryArgs = {
  entryId: DatabaseNodeId;
  fields: EntryFieldUpdate[];
  properties?: EntryPropertiesUpdate | null;
  password?: string | null;
};

export type DeleteEntryArgs = { entryId: DatabaseNodeId; permanent: boolean };

export type SaveDatabaseArgs = { password?: string | null };

export type GetCustomIconsArgs = Record<string, never>;

export type GetEntryTemplatesArgs = Record<string, never>;

export type MoveGroupArgs = {
  groupId: DatabaseNodeId;
  parentGroupId: DatabaseNodeId;
  destinationIndex: number;
};

export type MoveEntryArgs = { entryId: DatabaseNodeId; parentGroupId: DatabaseNodeId };

export type AddEntryArgs = { parentGroupId: DatabaseNodeId };

export type AddEntryFromTemplateArgs = {
  parentGroupId: DatabaseNodeId;
  templateEntryId: DatabaseNodeId;
};

export type AddGroupArgs = { parentGroupId: DatabaseNodeId };

export type DeleteGroupArgs = { groupId: DatabaseNodeId };

export type RenameGroupArgs = { groupId: DatabaseNodeId; name: string };

export type UpdateGroupArgs = { groupId: DatabaseNodeId; name: string; icon: IconReference };

export type UpdateTagStyleArgs = { name: string; style: TagStyle };

export type DeleteTagArgs = { name: string };

export type RevealEntryFieldArgs = {
  entryId: DatabaseNodeId;
  fieldId: string;
  password?: string | null;
};

export type GetPasskeysArgs = { rpId?: string | null };

/**
 * Registration inputs from a CTAP2 `authenticatorMakeCredential` request.
 */
export type RegisterPasskeyArgs = {
  rpId: string;
  rpName?: string | null;
  userName: string;
  userHandle: string;
  clientDataHash: string;
  algorithms: number[];
  excludeCredentialIds: string[];
  userVerified: boolean;
};

/**
 * Assertion inputs from a CTAP2 `authenticatorGetAssertion` request.
 */
export type AssertPasskeyArgs = {
  entryId: DatabaseNodeId;
  rpId: string;
  clientDataHash: string;
  userVerified: boolean;
};

export type Operation =
  | { op: 'open'; args: OpenArgs }
  | { op: 'create'; args: CreateArgs }
  | { op: 'unlock'; args: UnlockArgs }
  | { op: 'lock'; args: LockArgs }
  | { op: 'getDatabaseStatus'; args: GetDatabaseStatusArgs }
  | { op: 'getStorageDescriptor'; args: GetStorageDescriptorArgs }
  | { op: 'getConfig'; args: GetConfigArgs }
  | { op: 'setConfig'; args: SetConfigArgs }
  | { op: 'getEntries'; args: GetEntriesArgs }
  | { op: 'searchEntries'; args: SearchEntriesArgs }
  | { op: 'getGroupHierarchy'; args: GetGroupHierarchyArgs }
  | { op: 'getGroupEntries'; args: GetGroupEntriesArgs }
  | { op: 'getTagEntries'; args: GetTagEntriesArgs }
  | { op: 'getTrashEntries'; args: GetTrashEntriesArgs }
  | { op: 'getTags'; args: GetTagsArgs }
  | { op: 'getEntryDetail'; args: GetEntryDetailArgs }
  | { op: 'updateEntry'; args: UpdateEntryArgs }
  | { op: 'deleteEntry'; args: DeleteEntryArgs }
  | { op: 'saveDatabase'; args: SaveDatabaseArgs }
  | { op: 'getCustomIcons'; args: GetCustomIconsArgs }
  | { op: 'getEntryTemplates'; args: GetEntryTemplatesArgs }
  | { op: 'moveGroup'; args: MoveGroupArgs }
  | { op: 'moveEntry'; args: MoveEntryArgs }
  | { op: 'addEntry'; args: AddEntryArgs }
  | { op: 'addEntryFromTemplate'; args: AddEntryFromTemplateArgs }
  | { op: 'addGroup'; args: AddGroupArgs }
  | { op: 'deleteGroup'; args: DeleteGroupArgs }
  | { op: 'renameGroup'; args: RenameGroupArgs }
  | { op: 'updateGroup'; args: UpdateGroupArgs }
  | { op: 'updateTagStyle'; args: UpdateTagStyleArgs }
  | { op: 'deleteTag'; args: DeleteTagArgs }
  | { op: 'revealEntryField'; args: RevealEntryFieldArgs }
  | { op: 'getPasskeys'; args: GetPasskeysArgs }
  | { op: 'registerPasskey'; args: RegisterPasskeyArgs }
  | { op: 'assertPasskey'; args: AssertPasskeyArgs };

export type OperationRequest = (
  | { op: 'open'; args: OpenArgs }
  | { op: 'create'; args: CreateArgs }
  | { op: 'unlock'; args: UnlockArgs }
  | { op: 'lock'; args: LockArgs }
  | { op: 'getDatabaseStatus'; args: GetDatabaseStatusArgs }
  | { op: 'getStorageDescriptor'; args: GetStorageDescriptorArgs }
  | { op: 'getConfig'; args: GetConfigArgs }
  | { op: 'setConfig'; args: SetConfigArgs }
  | { op: 'getEntries'; args: GetEntriesArgs }
  | { op: 'searchEntries'; args: SearchEntriesArgs }
  | { op: 'getGroupHierarchy'; args: GetGroupHierarchyArgs }
  | { op: 'getGroupEntries'; args: GetGroupEntriesArgs }
  | { op: 'getTagEntries'; args: GetTagEntriesArgs }
  | { op: 'getTrashEntries'; args: GetTrashEntriesArgs }
  | { op: 'getTags'; args: GetTagsArgs }
  | { op: 'getEntryDetail'; args: GetEntryDetailArgs }
  | { op: 'updateEntry'; args: UpdateEntryArgs }
  | { op: 'deleteEntry'; args: DeleteEntryArgs }
  | { op: 'saveDatabase'; args: SaveDatabaseArgs }
  | { op: 'getCustomIcons'; args: GetCustomIconsArgs }
  | { op: 'getEntryTemplates'; args: GetEntryTemplatesArgs }
  | { op: 'moveGroup'; args: MoveGroupArgs }
  | { op: 'moveEntry'; args: MoveEntryArgs }
  | { op: 'addEntry'; args: AddEntryArgs }
  | { op: 'addEntryFromTemplate'; args: AddEntryFromTemplateArgs }
  | { op: 'addGroup'; args: AddGroupArgs }
  | { op: 'deleteGroup'; args: DeleteGroupArgs }
  | { op: 'renameGroup'; args: RenameGroupArgs }
  | { op: 'updateGroup'; args: UpdateGroupArgs }
  | { op: 'updateTagStyle'; args: UpdateTagStyleArgs }
  | { op: 'deleteTag'; args: DeleteTagArgs }
  | { op: 'revealEntryField'; args: RevealEntryFieldArgs }
  | { op: 'getPasskeys'; args: GetPasskeysArgs }
  | { op: 'registerPasskey'; args: RegisterPasskeyArgs }
  | { op: 'assertPasskey'; args: AssertPasskeyArgs }
) & { requestId: string };

export type EmptyResult = Record<string, never>;

export type DatabaseStatusResult = {
  status: DatabaseStatus;
  syncStatus: SyncStatus;
  dirty: boolean;
  syncError: OperationError | null;
};

export type StorageDescriptorResult = { storage: StorageDescriptor | null };

export type ConfigResult = { config: KeelessConfig };

export type EntriesResult = { entries: EntrySummary[] };

export type GroupHierarchyResult = {
  databaseName: string;
  rootGroupId: DatabaseNodeId;
  recycleBinId: DatabaseNodeId | null;
  groups: GroupHierarchyItem[];
};

export type TagsResult = { tags: TagSummary[] };

export type EntryDetailResult = {
  id: DatabaseNodeId;
  isTemplate: boolean;
  icon: IconReference;
  tags: string[];
  fields: EntryFieldInformation[];
  backgroundColor: string;
  foregroundColor: string;
  overrideUrl: string;
  creationTimeMs: number | null;
  lastModificationTimeMs: number | null;
  lastAccessTimeMs: number | null;
  locationChangedMs: number | null;
  expires: boolean;
  expiryTimeMs: number | null;
  usageCount: number;
  attachments: EntryAttachmentInformation[];
};

export type CustomIconsResult = { icons: CustomIcon[] };

export type AddEntryResult = { id: DatabaseNodeId };

export type AddGroupResult = { id: DatabaseNodeId };

export type RevealEntryFieldResult = { value: string };

/**
 * One stored passkey, as much as can be shown without signing anything.
 */
export type PasskeySummary = {
  entryId: DatabaseNodeId;
  credentialId: string;
  rpId: string;
  username: string;
  userHandle: string;
  algorithm: number;
};

export type PasskeysResult = { credentials: PasskeySummary[] };

export type RegisterPasskeyResult = {
  entryId: DatabaseNodeId;
  credentialId: string;
  authenticatorData: string;
};

export type AssertPasskeyResult = {
  credentialId: string;
  authenticatorData: string;
  signature: string;
  userHandle: string;
};

export type OperationSuccess =
  | { op: 'open'; result: EmptyResult }
  | { op: 'create'; result: EmptyResult }
  | { op: 'unlock'; result: EmptyResult }
  | { op: 'lock'; result: EmptyResult }
  | { op: 'getDatabaseStatus'; result: DatabaseStatusResult }
  | { op: 'getStorageDescriptor'; result: StorageDescriptorResult }
  | { op: 'getConfig'; result: ConfigResult }
  | { op: 'setConfig'; result: EmptyResult }
  | { op: 'getEntries'; result: EntriesResult }
  | { op: 'searchEntries'; result: EntriesResult }
  | { op: 'getGroupHierarchy'; result: GroupHierarchyResult }
  | { op: 'getGroupEntries'; result: EntriesResult }
  | { op: 'getTagEntries'; result: EntriesResult }
  | { op: 'getTrashEntries'; result: EntriesResult }
  | { op: 'getTags'; result: TagsResult }
  | { op: 'getEntryDetail'; result: EntryDetailResult }
  | { op: 'updateEntry'; result: EmptyResult }
  | { op: 'deleteEntry'; result: EmptyResult }
  | { op: 'saveDatabase'; result: EmptyResult }
  | { op: 'getCustomIcons'; result: CustomIconsResult }
  | { op: 'getEntryTemplates'; result: EntriesResult }
  | { op: 'moveGroup'; result: EmptyResult }
  | { op: 'moveEntry'; result: EmptyResult }
  | { op: 'addEntry'; result: AddEntryResult }
  | { op: 'addEntryFromTemplate'; result: AddEntryResult }
  | { op: 'addGroup'; result: AddGroupResult }
  | { op: 'deleteGroup'; result: EmptyResult }
  | { op: 'renameGroup'; result: EmptyResult }
  | { op: 'updateGroup'; result: EmptyResult }
  | { op: 'updateTagStyle'; result: EmptyResult }
  | { op: 'deleteTag'; result: EmptyResult }
  | { op: 'revealEntryField'; result: RevealEntryFieldResult }
  | { op: 'getPasskeys'; result: PasskeysResult }
  | { op: 'registerPasskey'; result: RegisterPasskeyResult }
  | { op: 'assertPasskey'; result: AssertPasskeyResult };

export type OperationError = { code: string; message: string };

export type OperationOutcome =
  | ({ status: 'success' } & OperationSuccess)
  | { status: 'error'; error: OperationError };

export type OperationResponse = OperationOutcome & { requestId: string };
