// Generated by `cargo run --bin export-types`. Do not edit.

export type MessageFrame = { version: 1; timestamp: number; nonce: string; ephemeralPublicKey: string | null; publicKey: string; payload: string | null; signature: string }

export type StorageDescriptor = { provider: string; path: string }

export type DatabaseStatus = "not_exist" | "locked" | "unlocked"

export type KeelessConfig = { autoLockTimeoutMs: number | null; paranoiaMode: boolean }

export type KeelessConfigPatch = { autoLockTimeoutMs?: number | null; paranoiaMode?: boolean }

export type OpenArgs = { storage: StorageDescriptor }

export type CreateArgs = { password: string }

export type UnlockArgs = { password: string }

export type LockArgs = Record<string, never>

export type GetDatabaseStatusArgs = Record<string, never>

export type GetConfigArgs = Record<string, never>

export type SetConfigArgs = { config: KeelessConfigPatch }

export type Operation = { op: "open"; args: OpenArgs } | { op: "create"; args: CreateArgs } | { op: "unlock"; args: UnlockArgs } | { op: "lock"; args: LockArgs } | { op: "getDatabaseStatus"; args: GetDatabaseStatusArgs } | { op: "getConfig"; args: GetConfigArgs } | { op: "setConfig"; args: SetConfigArgs }

export type OperationRequest = ({ op: "open"; args: OpenArgs } | { op: "create"; args: CreateArgs } | { op: "unlock"; args: UnlockArgs } | { op: "lock"; args: LockArgs } | { op: "getDatabaseStatus"; args: GetDatabaseStatusArgs } | { op: "getConfig"; args: GetConfigArgs } | { op: "setConfig"; args: SetConfigArgs }) & { requestId: string }

export type EmptyResult = Record<string, never>

export type DatabaseStatusResult = { status: DatabaseStatus }

export type ConfigResult = { config: KeelessConfig }

export type OperationSuccess = { op: "open"; result: EmptyResult } | { op: "create"; result: EmptyResult } | { op: "unlock"; result: EmptyResult } | { op: "lock"; result: EmptyResult } | { op: "getDatabaseStatus"; result: DatabaseStatusResult } | { op: "getConfig"; result: ConfigResult } | { op: "setConfig"; result: EmptyResult }

export type OperationError = { code: string; message: string }

export type OperationOutcome = ({ status: "success" } & OperationSuccess) | { status: "error"; error: OperationError }

export type OperationResponse = OperationOutcome & { requestId: string }

