// Generated by `cargo run --bin export-types`. Do not edit.

export type MessageFrame = { version: 1; timestamp: number; nonce: string; ephemeralPublicKey: string | null; publicKey: string; payload: string | null; signature: string }

export type StorageDescriptor = { provider: string; path: string }

export type DatabaseStatus = "not_exist" | "locked" | "unlocked"

export type KeelessConfig = { autoLockTimeoutMs: number | null; paranoiaMode: boolean }

export type KeelessConfigPatch = { autoLockTimeoutMs?: number | null; paranoiaMode?: boolean }

export type DatabaseNodeId = string | number

export type IconReference = { standardId: number; customUuid: string | null }

export type EntrySummary = { id: DatabaseNodeId; name: string | null; nameIsProtected: boolean; url: string | null; urlIsProtected: boolean; icon: IconReference; tags: string[] }

export type CustomIcon = { uuid: string; dataBase64: string; name: string; lastModificationTimeMs: number }

export type GroupHierarchyItem = { id: DatabaseNodeId; name: string; icon: IconReference; childGroupIds: DatabaseNodeId[] }

export type TagSummary = { name: string; entryCount: number }

export type EntryFieldInformation = { name: string; value: string | null; isProtected: boolean }

export type EntryAttachmentInformation = { name: string; size: number; isProtected: boolean }

export type OpenArgs = { storage: StorageDescriptor }

export type CreateArgs = { password: string }

export type UnlockArgs = { password: string }

export type LockArgs = Record<string, never>

export type GetDatabaseStatusArgs = Record<string, never>

export type GetStorageDescriptorArgs = Record<string, never>

export type GetConfigArgs = Record<string, never>

export type SetConfigArgs = { config: KeelessConfigPatch }

export type GetEntriesArgs = { excludeTrash?: boolean }

export type GetGroupHierarchyArgs = Record<string, never>

export type GetGroupEntriesArgs = { groupId: DatabaseNodeId }

export type GetTagEntriesArgs = { tag: string }

export type GetTrashEntriesArgs = Record<string, never>

export type GetTagsArgs = Record<string, never>

export type GetEntryDetailArgs = { entryId: DatabaseNodeId }

export type GetCustomIconsArgs = Record<string, never>

export type MoveGroupArgs = { groupId: DatabaseNodeId; parentGroupId: DatabaseNodeId; destinationIndex: number }

export type MoveEntryArgs = { entryId: DatabaseNodeId; parentGroupId: DatabaseNodeId }

export type Operation = { op: "open"; args: OpenArgs } | { op: "create"; args: CreateArgs } | { op: "unlock"; args: UnlockArgs } | { op: "lock"; args: LockArgs } | { op: "getDatabaseStatus"; args: GetDatabaseStatusArgs } | { op: "getStorageDescriptor"; args: GetStorageDescriptorArgs } | { op: "getConfig"; args: GetConfigArgs } | { op: "setConfig"; args: SetConfigArgs } | { op: "getEntries"; args: GetEntriesArgs } | { op: "getGroupHierarchy"; args: GetGroupHierarchyArgs } | { op: "getGroupEntries"; args: GetGroupEntriesArgs } | { op: "getTagEntries"; args: GetTagEntriesArgs } | { op: "getTrashEntries"; args: GetTrashEntriesArgs } | { op: "getTags"; args: GetTagsArgs } | { op: "getEntryDetail"; args: GetEntryDetailArgs } | { op: "getCustomIcons"; args: GetCustomIconsArgs } | { op: "moveGroup"; args: MoveGroupArgs } | { op: "moveEntry"; args: MoveEntryArgs }

export type OperationRequest = ({ op: "open"; args: OpenArgs } | { op: "create"; args: CreateArgs } | { op: "unlock"; args: UnlockArgs } | { op: "lock"; args: LockArgs } | { op: "getDatabaseStatus"; args: GetDatabaseStatusArgs } | { op: "getStorageDescriptor"; args: GetStorageDescriptorArgs } | { op: "getConfig"; args: GetConfigArgs } | { op: "setConfig"; args: SetConfigArgs } | { op: "getEntries"; args: GetEntriesArgs } | { op: "getGroupHierarchy"; args: GetGroupHierarchyArgs } | { op: "getGroupEntries"; args: GetGroupEntriesArgs } | { op: "getTagEntries"; args: GetTagEntriesArgs } | { op: "getTrashEntries"; args: GetTrashEntriesArgs } | { op: "getTags"; args: GetTagsArgs } | { op: "getEntryDetail"; args: GetEntryDetailArgs } | { op: "getCustomIcons"; args: GetCustomIconsArgs } | { op: "moveGroup"; args: MoveGroupArgs } | { op: "moveEntry"; args: MoveEntryArgs }) & { requestId: string }

export type EmptyResult = Record<string, never>

export type DatabaseStatusResult = { status: DatabaseStatus }

export type StorageDescriptorResult = { storage: StorageDescriptor | null }

export type ConfigResult = { config: KeelessConfig }

export type EntriesResult = { entries: EntrySummary[] }

export type GroupHierarchyResult = { databaseName: string; rootGroupId: DatabaseNodeId; recycleBinId: DatabaseNodeId | null; groups: GroupHierarchyItem[] }

export type TagsResult = { tags: TagSummary[] }

export type EntryDetailResult = { id: DatabaseNodeId; icon: IconReference; tags: string[]; fields: EntryFieldInformation[]; backgroundColor: string; foregroundColor: string; overrideUrl: string; creationTimeMs: number | null; lastModificationTimeMs: number | null; lastAccessTimeMs: number | null; locationChangedMs: number | null; expires: boolean; expiryTimeMs: number | null; usageCount: number; attachments: EntryAttachmentInformation[] }

export type CustomIconsResult = { icons: CustomIcon[] }

export type OperationSuccess = { op: "open"; result: EmptyResult } | { op: "create"; result: EmptyResult } | { op: "unlock"; result: EmptyResult } | { op: "lock"; result: EmptyResult } | { op: "getDatabaseStatus"; result: DatabaseStatusResult } | { op: "getStorageDescriptor"; result: StorageDescriptorResult } | { op: "getConfig"; result: ConfigResult } | { op: "setConfig"; result: EmptyResult } | { op: "getEntries"; result: EntriesResult } | { op: "getGroupHierarchy"; result: GroupHierarchyResult } | { op: "getGroupEntries"; result: EntriesResult } | { op: "getTagEntries"; result: EntriesResult } | { op: "getTrashEntries"; result: EntriesResult } | { op: "getTags"; result: TagsResult } | { op: "getEntryDetail"; result: EntryDetailResult } | { op: "getCustomIcons"; result: CustomIconsResult } | { op: "moveGroup"; result: EmptyResult } | { op: "moveEntry"; result: EmptyResult }

export type OperationError = { code: string; message: string }

export type OperationOutcome = ({ status: "success" } & OperationSuccess) | { status: "error"; error: OperationError }

export type OperationResponse = OperationOutcome & { requestId: string }

