import {
  IconAppWindow,
  IconApple,
  IconArchive,
  IconBadgeCheck,
  IconBatteryCharging,
  IconBookOpen,
  IconBookOpenText,
  IconCamera,
  IconCircleCheck,
  IconCircleDollarSign,
  IconClipboardCheck,
  IconClock,
  IconClockAlert,
  IconContact,
  IconDisc3,
  IconFeather,
  IconFileCheck,
  IconFileLock,
  IconFilePlus,
  IconFileQuestionMark,
  IconFlag,
  IconFolder,
  IconFolderCheck,
  IconFolderOpen,
  IconGlobe,
  IconHardDrive,
  IconHouse,
  IconImages,
  IconInfo,
  IconKeyRound,
  IconKeySquare,
  IconLandmark,
  IconList,
  IconLockKeyhole,
  IconLockOpen,
  IconMail,
  IconMailbox,
  IconMemoryStick,
  IconMessagesSquare,
  IconMonitor,
  IconMonitorCog,
  IconMonitorPlay,
  IconNotebookPen,
  IconPackage,
  IconPackageOpen,
  IconPanelsTopLeft,
  IconPenLine,
  IconPlay,
  IconPrinter,
  IconPuzzle,
  IconRadio,
  IconRadioTower,
  IconSave,
  IconScanLine,
  IconSearch,
  IconServer,
  IconSettings,
  IconSlidersHorizontal,
  IconSmartphone,
  IconSparkles,
  IconSquareTerminal,
  IconStar,
  IconStickyNote,
  IconTrash,
  IconTriangleAlert,
  IconUserRoundKey,
  IconWrench,
  IconZap,
} from '@/icons';
import type { ComponentType, SVGProps } from 'react';

export type StandardIcon = {
  id: number;
  label: string;
  searchTerms: string;
  Icon: ComponentType<SVGProps<SVGSVGElement>>;
};

const definitions = [
  ['Key', 'password security', IconKeyRound],
  ['Globe', 'world web internet', IconGlobe],
  ['Warning', 'alert caution', IconTriangleAlert],
  ['Network server', 'server network', IconServer],
  ['Marked folder', 'directory checked', IconFolderCheck],
  ['Messages', 'communication chat users', IconMessagesSquare],
  ['Puzzle', 'parts extension plugin', IconPuzzle],
  ['Notepad', 'notes notebook pen', IconNotebookPen],
  ['Radio tower', 'world socket antenna', IconRadioTower],
  ['Contact', 'identity person', IconContact],
  ['File checked', 'paper ready document', IconFileCheck],
  ['Camera', 'photo digicam', IconCamera],
  ['Radio', 'infrared communication', IconRadio],
  ['Keys', 'multiple key password', IconKeySquare],
  ['Energy', 'lightning power', IconZap],
  ['Scanner', 'scan line', IconScanLine],
  ['Sparkles', 'world star favorite', IconSparkles],
  ['Disc', 'cd media', IconDisc3],
  ['Monitor', 'screen computer', IconMonitor],
  ['Email', 'mail envelope', IconMail],
  ['Settings', 'configuration gear', IconSettings],
  ['Clipboard checked', 'clipboard ready', IconClipboardCheck],
  ['New file', 'paper document plus', IconFilePlus],
  ['Media screen', 'monitor play video', IconMonitorPlay],
  ['Battery charging', 'energy power', IconBatteryCharging],
  ['Mailbox', 'email box', IconMailbox],
  ['Save', 'disk floppy', IconSave],
  ['Hard drive', 'storage disk', IconHardDrive],
  ['File question', 'paper help unknown', IconFileQuestionMark],
  ['Locked', 'black lock secure', IconLockKeyhole],
  ['Encrypted terminal', 'console command line', IconSquareTerminal],
  ['Printer', 'print', IconPrinter],
  ['Application window', 'program icons software', IconAppWindow],
  ['Play', 'run start', IconPlay],
  ['Sliders', 'settings controls', IconSlidersHorizontal],
  ['Computer settings', 'monitor configuration', IconMonitorCog],
  ['Archive', 'compressed package', IconArchive],
  ['Bank', 'landmark home banking finance', IconLandmark],
  ['Panels', 'windows layout drive', IconPanelsTopLeft],
  ['Clock', 'time', IconClock],
  ['Search', 'find email', IconSearch],
  ['Flag', 'paper marker', IconFlag],
  ['Memory', 'ram stick', IconMemoryStick],
  ['Trash', 'recycle bin delete', IconTrash],
  ['Note', 'sticky memo', IconStickyNote],
  ['Expired', 'clock alert overdue', IconClockAlert],
  ['Information', 'info details', IconInfo],
  ['Package', 'box parcel', IconPackage],
  ['Folder', 'directory', IconFolder],
  ['Open folder', 'directory open', IconFolderOpen],
  ['Open package', 'folder package box', IconPackageOpen],
  ['Unlocked', 'lock open', IconLockOpen],
  ['Locked file', 'paper document secure', IconFileLock],
  ['Checked', 'circle check complete', IconCircleCheck],
  ['Pen', 'write edit', IconPenLine],
  ['Images', 'thumbnail photos gallery', IconImages],
  ['Book', 'read open', IconBookOpen],
  ['List', 'items menu', IconList],
  ['User key', 'account identity password', IconUserRoundKey],
  ['Tool', 'wrench maintenance', IconWrench],
  ['Home', 'house', IconHouse],
  ['Star', 'favorite', IconStar],
  ['Terminal', 'tux linux console', IconSquareTerminal],
  ['Feather', 'quill write', IconFeather],
  ['Apple', 'mac ios', IconApple],
  ['Wiki', 'book text documentation', IconBookOpenText],
  ['Money', 'dollar finance payment', IconCircleDollarSign],
  ['Certificate', 'badge verified check', IconBadgeCheck],
  ['Smartphone', 'blackberry mobile phone', IconSmartphone],
] as const;

// KeePass PwIcon values are positional, from Key (0) through BlackBerry (68).
export const standardIcons: StandardIcon[] = definitions.map(([label, searchTerms, Icon], id) => ({
  id,
  label,
  searchTerms,
  Icon,
}));
